services:
  app:
    image: popochoo/devops-for-developers-project-74:latest
    build:
      context: .
      dockerfile: Dockerfile.production
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
